# This is a basic workflow to help you get started with Actions

name: Simple startup 

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  schedule:
    - cron: '* * * * *'


jobs:
  my-job:
    name : my build
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo Hello There!!
  
 
